blacklistedOres = []
enableNoEmiMessage = true
spawnWithGuideBook = false
respawnWithGuideBook = false
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = false
enableHatchPlacementOverlay = true
colorWaterLava = true
enableDebugCommands = false
enableBidirectionalEnergyCompat = true
enableAe2Integration = true
enableFtbQuestsIntegration = false
generateOres = true
datagenOnStartup = false
loadRuntimeGeneratedResources = true
